### ISSUE TITLE
offer UI for collecting info from users

### ISSUE THREAD

**Issue by gregglind** [gregglind/micropilot#19]
Maybe a simple form, with https://github.com/ilanasegall/ctp-micropilot/blob/master/data/email.html as a straw implementation.

**Comment by ilanasegall** [comment]
Note: Implementation in https://github.com/ilanasegall/ctp-micropilot/blob/master/lib/main.js has slight bug; form pops up every time browser is restarted.

**Comment by gregglind** [comment]
solve this in #22
