### ISSUE TITLE
need volo version in documentation

### ISSUE THREAD

**Issue by monicachew** [gregglind/micropilot#34]
I started from a new directory and followed instructions https://github.com/gregglind/micropilot#install. Then I did cfx run and ran into 

mchew@mchew-12604:~/addons/mp-test$ volo add micropilot packages/micropilot
Using github repo "gregglind/micropilot" for "micropilot"...
mchew@mchew-12604:~/addons/mp-test$ cfx run
Traceback (most recent call last):
  File "/home/mchew/addons/addon-sdk-1.13.1/bin/cfx", line 33, in <module>
    cuddlefish.run()
  File "/home/mchew/addons/addon-sdk-1.13.1/python-lib/cuddlefish/**init**.py", line 650, in run
    pkg_cfg = packaging.build_config(env_root, target_cfg, options.packagepath)
  File "/home/mchew/addons/addon-sdk-1.13.1/python-lib/cuddlefish/packaging.py", line 260, in build_config
    pkgconfig = get_config_in_dir(path)
  File "/home/mchew/addons/addon-sdk-1.13.1/python-lib/cuddlefish/packaging.py", line 168, in get_config_in_dir
    path))
cuddlefish.packaging.MalformedPackageError: package.json not found in "/home/mchew/addons/mp-test/packages/micropilot"

mchew@mchew-12604:~/addons/mp-test$ ls packages/micropilot/
gregglind-micropilot-cab4e7d  micropilot.zip

I "fixed" this issue by moving packages/micropilot/gregglind-micropilot-foo to packages/micropilot, but I am sure that was the wrong thing to do...

**Comment by gregglind** [comment]
It should be at `packages/micropilot`

1) Make sure your `volo` is really new (version > 0.2.8)
2) that volo command should have been run from your root.
3) typically, I now suggest just starting from `gregglind/micropilot-template` which does a lot more of the work for you.

HOller if you want to walk through this in person.

**Comment by monicachew** [comment]
Thanks! I'll retry and report back. 

----- Original Message -----

**Comment by monicachew** [comment]
Sorry for the long delay. I couldn't force volo to be installed greater than 0.2.6 with npm. However, I still get errors when using gregglind/micropilot-template, and the latest addon sdk. 

mchew@mchew-12604:~/addons$ rm -rf myaddon 
mchew@mchew-12604:~/addons$ volo create myaddon micropilot-template 
Using github repo "gregglind/micropilot-template" for "micropilot-template"... 
Downloading: https://nodeload.github.com/gregglind/micropilot-template/legacy.zip/master 
Downloading: https://nodeload.github.com/gregglind/micropilot/legacy.zip/v0.8 

Installed github:gregglind/micropilot/v0.8 at packages/micropilot 
https://api.github.com/repos/gregglind/micropilot-template/zipball/master used to create myaddon 
mchew@mchew-12604:~/addons$ cd myaddon/ 
mchew@mchew-12604:~/addons/myaddon$ cfx run 
Traceback (most recent call last): 
File "/home/mchew/addons/addon-sdk/bin/cfx", line 33, in <module> 
cuddlefish.run() 
File "/home/mchew/addons/addon-sdk/python-lib/cuddlefish/**init**.py", line 687, in run 
pkg_cfg = packaging.build_config(env_root, target_cfg, options.packagepath) 
File "/home/mchew/addons/addon-sdk/python-lib/cuddlefish/packaging.py", line 260, in build_config 
pkgconfig = get_config_in_dir(path) 
File "/home/mchew/addons/addon-sdk/python-lib/cuddlefish/packaging.py", line 168, in get_config_in_dir 
path)) 
cuddlefish.packaging.MalformedPackageError: package.json not found in "/home/mchew/addons/myaddon/packages/micropilot" 
mchew@mchew-12604:~/addons/myaddon$ ls packages/micropilot/ 
gregglind-micropilot-cab4e7d micropilot.zip 

----- Original Message -----

**Comment by monicachew** [comment]
It was my volo version. Running with 0.2.9 fixes everything.

**Comment by gregglind** [comment]
This has been long enough that `npm install volo` installs a new enough volo.  This bug is the documentation.
